# Generated by Django 4.2.6 on 2023-11-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_history',
            field=models.ManyToManyField(blank=True, to='app1.passwordhistory'),
        ),
    ]
